CREATE TABLE IF NOT EXISTS "Patient" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"document_number" VARCHAR(20) NOT NULL UNIQUE,
	"document_type_id" INTEGER NOT NULL,
	"email" VARCHAR(150) NOT NULL UNIQUE,
	"name" VARCHAR(255) NOT NULL,
	"phone" VARCHAR(10),
	"address" VARCHAR(150),
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "Document_Type" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(50) NOT NULL UNIQUE,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "Doctor" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(255) NOT NULL,
	"email" VARCHAR(150) UNIQUE,
	"specialty_id" INTEGER NOT NULL,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "Specialty" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(100) NOT NULL,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "Insurance" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(100) NOT NULL,
	"coverage_percentage" DECIMAL(5,2) NOT NULL,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "Appointment" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"appointment_date" TIMESTAMP NOT NULL,
	"patient_id" INTEGER NOT NULL,
	"doctor_id" INTEGER NOT NULL,
	"treatment_id" INTEGER NOT NULL,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "Treatment" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"treatment_description" VARCHAR(255) NOT NULL,
	"treatment_cost" DECIMAL(10,2) NOT NULL,
	"insurance_id" INTEGER NOT NULL,
	"amount_paid" INTEGER NOT NULL,
	PRIMARY KEY("id")
);



-- Patient → Document_Type
ALTER TABLE "Patient"
ADD CONSTRAINT fk_patient_document_type
FOREIGN KEY ("document_type_id") REFERENCES "Document_Type"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

-- Doctor → Specialty
ALTER TABLE "Doctor"
ADD CONSTRAINT fk_doctor_specialty
FOREIGN KEY ("specialty_id") REFERENCES "Specialty"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

-- Treatment → Insurance
ALTER TABLE "Treatment"
ADD CONSTRAINT fk_treatment_insurance
FOREIGN KEY ("insurance_id") REFERENCES "Insurance"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

-- Appointment → Treatment
ALTER TABLE "Appointment"
ADD CONSTRAINT fk_appointment_treatment
FOREIGN KEY ("treatment_id") REFERENCES "Treatment"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

-- Appointment → Doctor
ALTER TABLE "Appointment"
ADD CONSTRAINT fk_appointment_doctor
FOREIGN KEY ("doctor_id") REFERENCES "Doctor"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

-- Appointment → Patient
ALTER TABLE "Appointment"
ADD CONSTRAINT fk_appointment_patient
FOREIGN KEY ("patient_id") REFERENCES "Patient"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;